# Generated by Django 5.2.5 on 2025-09-05 19:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_movie_info_hash_remove_movie_leechers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistmovie',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistmovie',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlistmovie',
            name='watch_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlistmovie',
            name='watch_later',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlistmovie',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlistmovie',
            name='last_watched',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='playlistmovie',
            name='tmdb_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='playlist_entries', to='api.movie'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistmovie',
            unique_together={('author', 'tmdb_id')},
        ),
        migrations.AddIndex(
            model_name='playlistmovie',
            index=models.Index(fields=['author', 'watch_later'], name='api_playlis_author__d80920_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistmovie',
            index=models.Index(fields=['author', 'watch_history'], name='api_playlis_author__c592ad_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistmovie',
            index=models.Index(fields=['author', 'completed'], name='api_playlis_author__9130db_idx'),
        ),
    ]
