# Generated by Django 5.2.5 on 2025-09-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playlistmovie_added_at_playlistmovie_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistmovie',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='playlistmovie',
            name='watched_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='playlistmovie',
            name='watch_history',
            field=models.BooleanField(default=True),
        ),
    ]
