# Generated by Django 5.2.5 on 2025-09-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_playlistmovie_completed_at_playlistmovie_watched_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistmovie',
            old_name='tmdb_id',
            new_name='tmdb',
        ),
    ]
