# Generated by Django 5.2.5 on 2026-03-15 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_device_id_customuser_is_guest'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('api', '0007_auto_20251004_2018'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rooms', '0004_alter_room_movie_id'),
        ('token_blacklist', '0013_alter_blacklistedtoken_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
