version: '2'

services:
    nginx: 
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 80:80
        volumes:
            - static_volume:/app/backend/movie/static/
            - ./docker/nginx/development:/etc/nginx/conf.d
            - /media/downloads:/media/downloads
        depends_on: 
            - backend

    backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        env_file:
            - ./backend/.env.production
        volumes:
            - static_volume:/app/backend/movie/static/
            - /media/downloads:/media/downloads
        expose:
            - 8000        
        depends_on:
            - db

    db:
        image: postgres:15
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./docker/postgres:/docker-entrypoint-initdb.d
        env_file:
            - ./backend/.env.production

volumes:
    static_volume: {}
    postgres_data: {}
