# Generated by Django 5.2.5 on 2025-10-06 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_hash', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=True)),
                ('password_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('current_timestamp', models.FloatField(default=0.0)),
                ('max_users', models.PositiveIntegerField(default=8)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rooms', to=settings.AUTH_USER_MODEL)),
                ('whitelisted_users', models.ManyToManyField(blank=True, related_name='whitelisted_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('authorized', 'Authorized'), ('guest', 'Guest')], default='guest', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_watched_timestamp', models.FloatField(default=0.0)),
                ('is_watching', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(related_name='joined_rooms', through='rooms.RoomUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
