# Generated by Django 5.2.5 on 2025-10-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='whitelisted_users',
        ),
    ]
