# Generated by Django 5.2.5 on 2025-10-07 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_whitelisted_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomuser',
            name='role',
        ),
        migrations.CreateModel(
            name='RoomUserPrivileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('play_pause', models.BooleanField(default=False)),
                ('choose_movie', models.BooleanField(default=False)),
                ('add_users', models.BooleanField(default=False)),
                ('remove_users', models.BooleanField(default=False)),
                ('change_privileges', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privilege_roles', to='rooms.room')),
            ],
            options={
                'unique_together': {('room', 'name')},
            },
        ),
        migrations.AddField(
            model_name='roomuser',
            name='privileges',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.roomuserprivileges'),
        ),
    ]
