# Generated by Django 5.2.5 on 2025-10-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_roomuser_role_roomuserprivileges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='movie_id',
            field=models.IntegerField(null=True),
        ),
    ]
