# Generated by Django 5.2.4 on 2025-07-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('info_hash', models.CharField(blank=True, default='', max_length=200)),
                ('seeders', models.IntegerField(default=0)),
                ('backdrop_path', models.CharField(blank=True, default='', max_length=200)),
                ('poster_path', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(default='201', max_length=8)),
                ('overview', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('download_path', models.CharField(blank=True, default='.', max_length=300)),
            ],
        ),
    ]
