# Generated by Django 5.2.5 on 2025-09-02 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('imdb', models.CharField(blank=True, default='', max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('info_hash', models.CharField(blank=True, default='', max_length=200)),
                ('seeders', models.IntegerField(default=0)),
                ('leechers', models.IntegerField(default=0)),
                ('backdrop_path', models.CharField(blank=True, default='', max_length=200)),
                ('poster_path', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(default='201', max_length=8)),
                ('overview', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('download_path', models.CharField(blank=True, default='.', max_length=300)),
                ('hls_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.IntegerField(default=0)),
                ('last_watched', models.DateField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_movie', to=settings.AUTH_USER_MODEL)),
                ('tmdb_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie', to='api.movie')),
            ],
        ),
    ]
