# Generated by Django 5.2.4 on 2025-07-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='leechers',
            field=models.IntegerField(default=0),
        ),
    ]
