# Generated by Django 5.2.5 on 2025-09-04 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='info_hash',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='leechers',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='seeders',
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='seconds', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
