# Generated by Django 5.2.4 on 2025-07-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_leechers'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
