# Generated by Django 5.2.4 on 2025-08-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_imdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hls_available',
            field=models.BooleanField(default=False),
        ),
    ]
