# Generated by Django 5.2.4 on 2025-08-30 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_hls_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.IntegerField(default=0)),
                ('last_watched', models.DateField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_movie', to=settings.AUTH_USER_MODEL)),
                ('tmdb_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie', to='api.movie')),
            ],
        ),
    ]
