# Generated by Django 5.2.5 on 2025-09-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_tmdb_id_playlistmovie_tmdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistmovie',
            name='watch_history',
            field=models.BooleanField(default=False),
        ),
    ]
